#include <iostream>
// #include <stdexcept>
// #include <string>
// #include <cctype>
#include <vector>
using namespace std;

class matrix
{
private:
    /* data */
public:
    matrix(/* args */);
    ~matrix();
};

matrix::matrix(/* args */)
{
}

matrix::~matrix()
{
}


bool compare(matrix &m1, matrix &m2);
vector<int>::iterator change_val(int, vector<int>::iterator);


int main()
{

    
    cout << "\n\n";
    system("pause");
    return 0;
}